### PR TITLE
feat: added minimal pr checker and comment workflow

### LINKED ISSUE #745: Feature: Create action to comment on PR's that have no linked issues.

### PR DESCRIPTION
**Pull request by 0-vortex**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Related Tickets & Documents

Closes #745 

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

- this workflow will not run until merged to default branch
- current pull check runs on every action - should maybe check if the bot has previous comments

### CODE REVIEW

**Comment by 0-vortex** [comment]
@open-sauced/triage what do you think about having this running on pull request creation and maybe modify the message to ping the triage team ?

**Comment by filiptronicek** [comment]
This looks like a helpful workflow, I like it. We could add more rules as we go on, but this is a good one to start with.

**Comment by mtfoley** [comment]
hey @0-vortex would the plan be to pick this back up in `open-sauced/actions` repo?

With the semantic release stuff back in place I could see this still being a worthwhile endeavor.

**Comment by 0-vortex** [comment]
> hey @0-vortex would the plan be to pick this back up in `open-sauced/actions` repo?
> 
> With the semantic release stuff back in place I could see this still being a worthwhile endeavor.

totally forgot about this, it's missing some quality of life improvements around first-time contributors, double-checking the condition and giving it better output maybe. Would love this to be part of our actions repo but still feels like a draft without some improvements :<

**Comment by mtfoley** [comment]
So I've looked thru this list and looked over the code for some of these actions that seem most applicable. https://github.com/sdras/awesome-actions

As an unpracticed practitioner I would propose we make our own action that checks for:
- key phrases in the PR description, as needed for release automation
- whether or not package.json / npm-shrinkwrap.json were affected
- whether or not PR title is Ok for semantic release. 
This way we could tailor an automated comment to the diff things that the contributor would need to address.

**Comment by mtfoley** [comment]
been playing with an action tonight to look at what i was proposing...

https://github.com/mtfoley/pr-lint-action/blob/feat-body-regex/src/main.ts

**Comment by bdougie** [comment]
I don't think this should be open-sauced/actions. Primarily because this is contributor specific to this project. How it would be nice in the `.github/workflows/compliance.yml`

**Comment by 0-vortex** [comment]
closing this in favor of @mtfoley superset action

**Pull request closed without merging**
