### PR TITLE
feat: Change use-shopping-cart logo

### LINKED ISSUE #1084: Feature: Update logo for use-shopping-cart
### Is your feature request related to a problem? Please describe.

During the implementation of dark mode, it came up that the logo for use-shopping-cart on the splash page should be updated. Looks like with their release 3.0, there's a new logo in use.

### Describe the solution you'd like

Update the logo to the one in use at https://useshoppingcart.com

### Describe alternatives you've considered

N/A

### Additional context

Screenshot of existing logo, mobile safari
image

### PR DESCRIPTION
**Pull request by daptheHuman**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [X] ✨ Feature
- [ ] 🐛 Bug Fix
- [X] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR replaces the old "use-shopping-cart" logo into the new one, that the https://useshoppingcart.com uses

## Related Tickets & Documents
Fixes #1084 

## Mobile & Desktop Screenshots/Recordings
image

## Added tests?

- [X] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 docs
- [ ] 📕 storybook
- [X] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?
N/A

## [optional] What gif best describes this PR or how it makes you feel?
smiley

### CODE REVIEW

**Comment by 0-vortex** [comment]
LGTM!

Screenshot 2021-07-17 at 07 53 16

**Comment by filiptronicek** [comment]
> LGTM!
> 
> 
> 
> Screenshot 2021-07-17 at 07 53 16
> 
> 

@0-vortex as a follow up, it seems that the contrast on the logos is pretty low, maybe we could make an issue about that?

**Comment by 0-vortex** [comment]
> > LGTM!
> > Screenshot 2021-07-17 at 07 53 16
> 
> @0-vortex as a follow-up, it seems that the contrast on the logos is pretty low, maybe we could make an issue about that?

Oh snap I didn't even see there was a cart there :D 
A bit conflicted about what a good solution for that would be - looking at the logo a yellow outline could fix or ruin it, but should totally open up an issue about that!

**Comment by filiptronicek** [comment]
@0-vortex what about we make every logo card? A box with its own contrasting background?

**Comment by daptheHuman** [comment]
@0-vortex @filiptronicek i dont even notice on dark mode😂 i went to the light mode that time

**Comment by 0-vortex** [comment]
> @0-vortex what about we make every logo card? A box with its own contrasting background?

Yeah that's what I was thinking, it's either beautiful or bust :D

**Pull request merged**
