### PR TITLE
fix: 971 pagination for issues

### LINKED ISSUE #971: Bug: next/prev buttons don’t work for repo issues
### To Reproduce

1. Open a goal from the dashboard.
2. Note the issues list for the repo, click “Next”

### Expected behavior
Page would load next group of issues
### Screenshots
71CE6312-F256-4A12-A63C-7F6B507BC613

### PR DESCRIPTION
**Pull request by bdougie**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [x] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

fixes #971

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
https://www.loom.com/share/c1492ca3614644fd9f427f9a2baacfbd

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

#976

### CODE REVIEW

**Comment by mtfoley** [comment]
No joy on the Netlify [Preview](https://deploy-preview-977--open-sauced.netlify.app/). Same behavior for me.

**Comment by bdougie** [comment]
> No joy on the Netlify [Preview](https://deploy-preview-977--open-sauced.netlify.app/). Same behavior for me.

Are you able to make a gif or recording? Can clear your cache and try again?

**Comment by mtfoley** [comment]
On iPhone...

https://user-images.githubusercontent.com/3792749/116822332-4c3f1980-ab4c-11eb-98fb-9cd31f684376.MP4

**Comment by bdougie** [comment]
Ah, got it. It works for open sauced, but nothing else. I saw that mentioned earlier too. I will look into it.

**Comment by bdougie** [comment]
Fixed issue with issues in https://github.com/open-sauced/open-sauced/pull/977/commits/6fd72db5924a9aa46ef2f1dff870e0d5b6e7ab6a

**Comment by bdougie** [comment]
Merging to unblock folks. Also taking a look at #973 now

**Pull request merged**
