### PR TITLE
Add an empty placeholder for goals

### LINKED ISSUE #608: Show empty placeholder if no there are repos
Show empty placeholder if no there are repos

### To Reproduce

1. Close all issues in goals repo

### Expected behavior

Show a placeholder that no repo exists

### Screenshots

Screenshot

### PR DESCRIPTION
**Pull request by yg**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [x] Optimization
- [ ] Documentation Update
- [ ] Release

## Description

Add an empty placeholder for goals

## Related Tickets & Documents

Closes #608 

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

https://www.loom.com/share/61d3dba97eb94f0396a49f867cda341a

## Added tests?

- [ ] yes
- [ ] no, because they aren't needed
- [x] no, because I need help

## Added to documentation?

- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by yg** [comment]
Oops! The test is failing!

**Comment by yg** [comment]
> Oops! The test is failing!

Fixed, The reason is I placed the condition in the wrong file!

**Comment by bdougie** [comment]
What we can use instead of the rocket?

**Comment by yg** [comment]
> What we can use instead of the rocket?

@bdougie WDYT about this?

Screenshot

**Pull request merged**
