### PR TITLE
feat: [WIP] service worker toast

### LINKED ISSUE #1358: Feature: add service worker notifications
### Type of feature

Feature

### Current behavior

When open-sauced is ready to be used offline the user isn't notified visually unless they open the web inspector and check the `console.log`s

### Desired solution

1. Implement some toast notification like:
- https://github.com/fkhadra/react-toastify
- https://github.com/timolins/react-hot-toast
- https://github.com/iamhosseindhv/notistack
- https://github.com/react-component/notification
2. Update https://github.com/open-sauced/open-sauced/blob/0e0c13344dcb4c684fecdb91e5c38515af799fb3/src/index.jsx#L27-L40 to reflect visual notifications for offline-first web workers

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mtfoley**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR closes adds toast notification to indicate changes in service worker.  Could be used for other notifications in the future.

## Related Tickets & Documents

This PR closes #1358 

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?
angry toast

### CODE REVIEW

**Comment by 0-vortex** [comment]
not a big fan of goober 🤷

**Comment by mtfoley** [comment]
> not a big fan of goober 🤷

Is that the GIF? I typed “toaster” into giphy and here we are

**Comment by 0-vortex** [comment]
> > not a big fan of goober 🤷
> 
> Is that the GIF? I typed “toaster” into giphy and here we are

the css-in-js solution the toaster is using :D

**Comment by mtfoley** [comment]
Ah ok. I had just picked one from your list. I’ve got 5mins in it so open to a different one.

**Comment by mtfoley** [comment]
> Ah ok. I had just picked one from your list. I’ve got 5mins in it so open to a different one.

TODO: choose from:
- https://github.com/fkhadra/react-toastify: looks like it uses SCSS
- ~~https://github.com/timolins/react-hot-toast: uses whatever goober is~~
- https://github.com/iamhosseindhv/notistack: maybe uses @emotion/styled / material UI
- https://github.com/react-component/notification: looks like it uses LESS: https://github.com/react-component/notification/blob/master/assets/index.less

@0-vortex any commentary on these?

**Comment by 0-vortex** [comment]
notis is very popular but I would go with the one that works the best for you; essentially if it installs and is usable :D

**Pull request closed without merging**
