### PR TITLE
feat: update notebox story

### LINKED ISSUE #1160: Feature: Update the the NoteBox storybook stories
### Type of feature

Style

### Current behavior

[Link to the design story](https://github.com/open-sauced/open-sauced/blob/main/stories/2-Card.stories.js#L154-L174)

### Desired solution

It should mirror what is live in production. 

### Additional context

Please ask questions if you are considering taking this on.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ilangorajagopal**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [x] ✨ Feature
- [x] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR updates the `NoteCard` story and includes the Basic Template link. It also fixes the `SubtleLink` color in light mode.

## Related Tickets & Documents

Fixes #1160 

### Before

Cards-Note-Card-⋅-Storybook-before

#### Light Mode

Cards-Note-Card-⋅-Storybook-after-dark

#### Dark Mode

Cards-Note-Card-⋅-Storybook

#### Before

NoteCard-before

#### After

Light Mode:

Open-Sauced

Dark Mode:

Open-Sauced-dark

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 docs
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by mtfoley — COMMENTED** [review]
@ilangorajagopal thanks for working on this.  If I search for "SubtleLink" in the codebase, I see it in a few places (mainly here and in the navigation). The navigation doesn't change color appreciably in dark mode, hence the lack of adjustment. 

https://github.com/open-sauced/open-sauced/search?q=SubtleLink 

I think this was my fault for including it as a suggestion in a prior PR.  Instead of changing the style definition of SubtleLink, we might be better served by using a standard <a> tag or by defining a new item of typography.

**Review by mtfoley — COMMENTED** [review]
The previous implementation of the NoteCard in storybook built up a similar layout to what was in the files `src/styles/TextArea.js`, `src/components/NoteForm.js` (since deleted, but you can see it here: https://github.com/open-sauced/open-sauced/blob/9fc4d9a75f8d3934cd35122c70831e8c93697fc8/src/components/NoteForm.js

I think what might be preferable to do here is to import the NoteForm component from `src/components/NoteFormSocial.js`, give it a few props to show some text, and and export that as the named export inside `stories/2-Card.stories.js`.

Let me know on here or in the [Discord](https://discord.com/invite/U2peSNf23P) if that doesn't make sense.

**Comment by ilangorajagopal** [comment]
Sure. 

> Regarding the use of Subtle link, I think it could use AccentLink instead

Just confirming. I should update both the component and the story with AccentLink, right?

**Comment by 0-vortex** [comment]
Any way we can help with this?

**Pull request closed without merging**
