### PR TITLE
fix: safari bug

### LINKED ISSUE #1048: Bug: Dark Mode Theme Button Shows Wrong in Safari
### Describe the bug
The theme button that overrides user's system preference to active dark mode (it's a moon icon) doesn't have the rotation right in Safari. From what I've read briefly, there is probably a fix by editing the SVG markup: https://stackoverflow.com/questions/48248512/svg-transform-rotate180-does-not-work-in-safari-11

### To Reproduce
1) Open opensauced.pizza in Safari for MacOS or iOS.

### Expected behavior
Moon icon is shown with moon at 45 deg angle facing upper right.

### Screenshots
bottom of screenshot is safari, top is chrome.
Screen Shot 2021-06-16 at 10 17 37 PM

### Desktop

- OS: mac
- Browser: Safari
- Version: v14.1.1

### Smartphone

- Device: iphone 8
- OS: iOS
- Browser: safari
- Version: latest, dunno

### PR DESCRIPTION
**Pull request by jason1985**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [x] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR fixes a Safari SVG bug.

## Related Tickets & Documents

Fixes #1048 

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 docs
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by mtfoley** [comment]
We can prob reproduce but can you take screenshots of your fix? I saw the note in the issues list where you were asking about safari but I just now saw this so I assumed you worked it out.

**Comment by jason1985** [comment]
Hi @mtfoley.  I haven't had the chance to test it properly, the latest supported version of Safari on Windows doesn't work with opensauced.pizza.
I did deploy my svg fixed version of open-sauced on https://jason1985.github.io/open-sauced/ .
So when I have access to iOS or Safari I can check it there & add screenshots.

**Comment by mtfoley** [comment]
@jason1985 thanks for the update. Below are a couple of screenshots from mobile safari. It looks like the dark mode icon lost its centering somehow.image

**Comment by jason1985** [comment]
@mtfoley I found the issue and updated the PR.
It should work ok now as I got it displaying correctly on my local version of Safari.
Screenshot below is old SVG compared with new.
Thanks.
image

**Comment by mtfoley** [comment]
LGTM. @bdougie do you want to see if all ok to merge? I believe checks are picking up the first time contributor.
Safari on iOS : 
image
Chrome on iOS:
image

@jason1985 you may catch it on https://twitch.tv/bdougieyo if he looks at this one on stream.

**Comment by jason1985** [comment]
@mtfoley cool!  I'll be watching the stream.  Thanks!

**Review by bdougie — APPROVED** [review]
Thanks so much for jumping on this @jason1985

**Comment by jason1985** [comment]
Thank you @bdougie!  I'm happy to learn and get familiar using github.

**Comment by 0-vortex** [comment]
> Hi @mtfoley. I haven't had the chance to test it properly, the latest supported version of Safari on Windows doesn't work with opensauced.pizza.
> I did deploy my svg fixed version of open-sauced on https://jason1985.github.io/open-sauced/ .
> So when I have access to iOS or Safari I can check it there & add screenshots.

Just a heads up, that version of safari is deprecated, testing on it can get really confusing. Appreciate you fixing the SVG itself !!

**Comment by jason1985** [comment]
Thanks!  I'm having fun learning how to use github.  I hope to contribute more!

**Pull request merged**
