### PR TITLE
Filter and Sort Goals by name and stars

### LINKED ISSUE #762: Feature: Sort Goals
### Describe the solution you'd like

Sort Goals by

- name
- last updated
- stars

we can use **lodash** to achieve it cuz we are not using pagination for this!

### Additional context

Screenshot

### PR DESCRIPTION
**Pull request by yg**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

Sort Goals by name and stars and also added search

## Related Tickets & Documents

Closes #762 

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

https://www.loom.com/share/95ada7bfc0a14f5f8fe7f6fcd2d22762

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by filiptronicek** [comment]
What if the first character of the org/user is a period? Should it be before A or after Z when sorting alphabetically? @yg

**Comment by filiptronicek** [comment]
@yg any idea why this happened?
image

**Comment by yg** [comment]
> @yg any idea why this happened?

Not sure why it is happening! Can you say the steps to reproduce it @filiptronicek?

**Comment by filiptronicek** [comment]
I just made a repo, called it three dots (filiptronicek/...) and it probably failed to sync the star count or something

**Comment by yg** [comment]
> I just made a repo, called it three dots (filiptronicek/...) and it probably failed to sync the star count or something

@filiptronicek I think it must be a separate issue and not related to this PR! Can you please create an issue for that!

PS: Check your actions log

**Comment by filiptronicek** [comment]
Sure, I will

**Comment by yg** [comment]
Moved sort option to the right, But it seems like we have lot of white spaces, Any suggestions to what can be filled there?

Screenshot

**Comment by filiptronicek** [comment]
> 
> 
> Moved sort option to the right, But it seems like we have lot of white spaces, Any suggestions to what can be filled there?
> 
> Screenshot

A search box!

**Comment by yg** [comment]
> A search box!

https://github.com/open-sauced/open-sauced/pull/765#issuecomment-653538108

**Comment by yg** [comment]
Can we add "sort by forks" too?

**Comment by filiptronicek** [comment]
> 
> 
> > Moved sort option to the right, But it seems like we have lot of white spaces, Any suggestions to what can be filled there?
> > Screenshot
> 
> A search box!

If I can elaborate on my search box suggestion, I think it would be awesome to implement something like this: https://www.npmjs.com/package/lunr. It would enable to make the searching more dynamic, without the struggles, WDYT? @open-sauced/triage

**Comment by yg** [comment]
Feedbacks welcome for this Implementation :purple_heart: 

Deploy Preview: https://deploy-preview-765--open-sauced.netlify.app/

https://www.loom.com/share/95ada7bfc0a14f5f8fe7f6fcd2d22762

**Comment by yg** [comment]
Added `EmptyPlaceholder` if there are no results!

https://www.loom.com/share/45ea5d4a9762436f90540110c7f3eafd

**Comment by yg** [comment]
@bdougie It is good to go now! Open for suggestions!

**Pull request merged**
