### PR TITLE
Skeleton Loading instead of "Loading..."

### PR DESCRIPTION
**Pull request by yg**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

Skeleton Loading instead of "Loading..."

## Related Tickets & Documents

#752

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

| Without Skeleton | With Skeleton|
|---|---|
| Screenshot | Screenshot |

https://www.loom.com/share/35077fa6126b408db858463f55b99e55

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by yg** [comment]
Add loading for contributions too

https://www.loom.com/share/afdd5dac82ea4db18c3a3bad8cc2c57a

**Comment by yg** [comment]
Added Meta loading in contributions list too

https://www.loom.com/share/35077fa6126b408db858463f55b99e55

**Comment by filiptronicek** [comment]
I really like this, it looks very dynamic. @yg

**Comment by filiptronicek** [comment]
However, I would prefer, if it would fit in better and be the same size as the text (it that is possible) @yg
unloaded
loaded

**Comment by filiptronicek** [comment]
You should be able to set the width pretty easily: https://www.npmjs.com/package/react-loading-skeleton#width

**Comment by JapneetSingh5** [comment]
This looks great!! Nice addition!

**Comment by bdougie** [comment]
I think the note in the context box should also include a skeleton until the title and languages are loaded. It looks odd with the text, but no title.  

image

**Comment by yg** [comment]
Added Loading for IssueListItem

https://www.loom.com/share/43a6a4dbafa54a1dac56c2a131889eee

**Comment by yg** [comment]
> I think the note in the context box should also include a skeleton until the title and languages are loaded. It looks odd with the text, but no title.

@bdougie We removed that line in this PR https://github.com/open-sauced/open-sauced/pull/733

Unfortunately just saw this PR has `master` as a base instead of `release`, we can make a separate PR for that after this week's release.

**Comment by filiptronicek** [comment]
The tests probably don't like the changed structure with the new Skeleton templates @yg 
logs

**Comment by bdougie** [comment]
One change I would add is switching this:

https://github.com/open-sauced/open-sauced/blob/master/src/components/Repository.js#L73

to {repoOwner}/{repoName} from the `match` prop

**Comment by yg** [comment]
@bdougie and @filiptronicek Added Skeleton loading for the New button area on the right, the loading color must be changed any suggestions?

Now {repoOwner}/{repoName} come from the `match` prop so it can load very fast!

https://www.loom.com/share/4b70cf8d3c6a4b3487be14aa289695ae

**Comment by filiptronicek** [comment]
Hi, I think we should reopen this or add a fix to 0.17.0, because it is a bit broken on mobile! @bdougie @yg 
screenshot

**Pull request merged**
