### PR TITLE
feat: storybook dark mode

### PR DESCRIPTION
**Pull request by mtfoley**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

Attempting to add feature #1053 but I know there's some changes to storybook being kicked around. FWIW, the only way i could get storybook to run was to upgrade it and gut the `.storybook/main.js`. To get all style effects in place I needed to copy `./src/index.css` to `.storybook/` so I could serve it as static asset. 

## Related Tickets & Documents

Attempting to add feature #1053 
## Mobile & Desktop Screenshots/Recordings

Screen Shot 2021-06-27 at 9 56 04 PM

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 docs
- [x] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?
no idea

### CODE REVIEW

**Comment by mtfoley** [comment]
womp womp, checks fail on dependency stuff. I chose not to commit my npm-shrinkwrap.json on purpose, maybe that was a mistake...

**Comment by bdougie** [comment]
running `npm ci` should fix it. You will need to commit the shrinkwrap.json too.

**Comment by mtfoley** [comment]
@bdougie looks like checks are passing now. Maybe there's a slight improvement to make by putting the `src/index.css` and maybe font files in a folder and serving them as static files. Let me know if you want to try to roll that into this PR since it already updates the `npm run storybook` script. Could also be a good first issue but with infra decisions coming up, I could see going either way.

**Comment by bdougie** [comment]
> Could also be a good first issue but with infra decisions coming up, I could see going either way.
I would say go for it!

**Review by bdougie — APPROVED** [review]

**Comment by 0-vortex** [comment]
Encountered the same issues @mtfoley did with webpack on the fixed dependencies main branch, attempting to fix some of them I replicated some of your work. Will fork your branch and consolidate upstream into it, then open a pull request to your this pull, it should align modifications to just the storybook packages and bypass the resolve conflicts button - assuming storybook works for everybody.

cc @filiptronicek from discord discussion

**Comment by 0-vortex** [comment]
Storybook addons could use very minor tweaking like some links or disabling the warning message in console but this seems solid and good to go!

Regarding infrastructure changes we could use the github cache on storybook, enable deployment to a specific subfolder of storybook like  `./.storybook/static` - this would work as expected if we follow the docs and then we could have a separate workflow or check whether it was manually ran to apply `npm run storybook -- --no-manager-cache` or just clear the cached github action container - a netlify storybook preview, similar to the one on pull request would be, in my opinion, cooler  however don't think the infra PR blocks this, rather the other way around 🔥

**Comment by bdougie** [comment]
Going to merge as is and avoid the scope creep as suggested on stream.

**Pull request merged**
