### PR TITLE
ci(workflow): add cache to workflows using actions/setup-node

### PR DESCRIPTION
**Pull request by oscard0m**
## Description

Add `cache` to workflows using `actions/setup-node`

## Context

`setup-node` GitHub Action just released a new option to add cache to steps using it.

You can find the details here: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/

---

🤖 This PR has been generated automatically by [this octoherd script](https://github.com/oscard0m/octoherd-script-add-cache-to-node-github-action), feel free to run it in your GitHub user/org repositories! 💪🏾

### CODE REVIEW

**Comment by 0-vortex** [comment]
LGTM!

**Comment by mtfoley** [comment]
@0-vortex github actions no likey… CI step gets an odd error.
609A78A4-929B-454C-B474-A9EA70D4CF82

**Comment by 0-vortex** [comment]
> @0-vortex github actions no likey… CI step gets an odd error.
> 609A78A4-929B-454C-B474-A9EA70D4CF82

Checked the code out and unfortunately the implementation passed working fully with `yarn` or `npm` modules: https://github.com/akv-platform/setup-node/blob/cfe70f9fe8ca345bad2e02a88695dd317e6172c0/src/cache-utils.ts#L15

Considering the fact that we also have a Netlify preview, for a complete cache implementation, at least what concerns GitHub actions, we would need a `main` cache key and a `pr-#number` wildcard cache key. I previously opposed the idea of creating a duplicate workflow file for `pr` and `release`, citing `actions/cache` complexities around security best practices and `actions/setup-node` planning a cache feature; however currently that's the only solution.

**Comment by filiptronicek** [comment]
@0-vortex how do you recommend we shall proceed? Is this drawback (I'm sure this will be a hassle because of a lot of duplicate code) worth sucking up for the performance boost?

**Comment by 0-vortex** [comment]
Would personally say yes but that's pushing things a bit in the direction of standardized operations and handling security best practices out of the hands of maintainers and into the hands of everyone - in perspective a good thing but implemented too quick or in a much too complex way could hurt beyond writing multiple versions of similar docs.

Not sure anyone except @bdougie has a transparent view of the cost of gha and netlify. Thinking about both deployment types, potentially adding storybook, we would gain most out of re-using installs when they happen in succession. Some valid use cases I can see here are:
- create new feature with added deps, start commiting without open PR, use no cache or production deps
- once a pull request is opened we can use a pull request number for the cache key subsequent builds would be optimised
- once a pull request build passes we could use the previous cache 

The above example are not inclusive and just meant to underline the security quirks involved with cache poisoning and multi-platform builds. 

Only combination matrix that I can see satisfying all our use cases is node cache, release and pull request workflows culminating in a docker tag that we can use as preview - in the docker ecosystem we could run several security audits both from actions or other docker containers and that would remove some complexity and generic attack vectors.

If a docker build deployed to any(multiple) registry is convenient, this issue can be split in 2 (node action cache and docker build) and handle all the possible performance optimisations we can think of.

**Comment by bdougie** [comment]
Hey jumping in to add my thoughts. 

I think with the complexity of docs, storybooks, and the app - a dockerize deployment strategy is worth exploring. 

With that said, I think we can consider a caching solution that uses multiple workflows for each situation. I don't know if a [composite-run steps](https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action) would help with the reusability and handle the complexity of checking which caching strategy could be used.

**Comment by bdougie** [comment]
Linking this issue as I think it is relevant. 

https://github.com/actions/setup-node/issues/286

**Comment by 0-vortex** [comment]
Can safely close this as we cannot use the cache key until `npm` is supported again. Can replicate the cache with `actions/cache` but I think it's a lot of work and little benefit without docker tagging - would do the docker build and push to Docker and GitHub registries before re-tackling the node cache issues honestly.

**Pull request closed without merging**
