### PR TITLE
Open Sauced name on browser console

### LINKED ISSUE #701: Feature: Open Sauced name on browser console
### Describe the solution you'd like

Just a small fun!

Open Sauced name with pizza on browser console

:wink: 

### Additional context

Screenshot from 2020-06-17 20-15-40

Inspired from dev.to

Screenshot from 2020-06-17 20-19-58

### PR DESCRIPTION
**Pull request by yg**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [x] 🚩 Other

## Description

#701

## Related Tickets & Documents

Closes #701

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

Screenshot from 2020-06-17 20-15-40

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by yg** [comment]
Screenshot from 2020-06-17 20-49-41

**Comment by bdougie** [comment]
I Like the idea, but I think we could make it more visually appealing, like the suggestions in #701. 

Can we get ASCII in there and use the [color palette from the site](https://github.com/open-sauced/open-sauced/blob/master/src/styles/variables.js#L2-L20).

**Comment by bdougie** [comment]
@open-sauced/triage team. Do you have any suggestions here?

**Comment by filiptronicek** [comment]
Love it! @yg. Super cool. How did you make the ASCII art?

**Comment by yg** [comment]
I used this to generate it http://patorjk.com/software/taag/#p=display&f=ANSI%20Shadow&t=Open%20Sauced

**Comment by akshay5995** [comment]
So cool! 🍕

**Pull request merged**
