### PR TITLE
Trim whitespace while adding the repo

### LINKED ISSUE #580: Including spaces before or after repo name adds an item to the list
### Describe the bug

When adding a space before or after the input when trying to add a repository results in the item being added to the list. When clicking the item it opens a page that display loading spinner indefinitely with no "not found" error. I noticed this when trying to paste a copy the owner/repo text from the repo's page, the pasted text included spaces which I forget to remove from the end. Adding repos like this **might** be a common method for users and they might also forget to remove the trailing space.

### To Reproduce
1. Enter the **correct** name of a repo
2. Include a space before and or after the repo
3. Watch as the repo is added

### Expected behavior
An error message should be displayed and the item should not be added to the list.

### Screenshots

Evidence of erroneous repo in list

Evidence of erroneous repo URL

### PR DESCRIPTION
**Pull request by yg**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Release

## Description

- [x] Trim whitespace while adding the repo
- [x] Trim whitespace even if the issue title is edited in GitHub
- [x] Trim whitespace in Repo avatar

## Related Tickets & Documents

Closes #580

### CODE REVIEW

**Comment by yg** [comment]
@Brawrdon Can you check now in the deployment URL?

**Comment by Brawrdon** [comment]
Removing white space from the start and end of the string works fine but they should be removed from the entire string. Copying and pasting the title from Github adds a space before the / and a new line after, which is interpreted as a space on a single line input box.

**Comment by bdougie** [comment]
@yg are you able to also add a test for this as well?

**Comment by yg** [comment]
@bdougie Let me try, I don't have any experience of writing tests, I will learn :smile:

**Comment by yg** [comment]
I think this will help https://stackoverflow.com/questions/41451729/react-how-to-simulate-user-input-for-unit-testing

**Comment by yg** [comment]
> Removing white space from the start and end of the string works fine but they should be removed from the entire string. Copying and pasting the title from Github adds a space before the / and a new line after, which is interpreted as a space on a single line input box.

@Brawrdon It's fixed now, can you check it in **deploy preview**?

**Comment by Brawrdon** [comment]
Seems to be working perfectly!

**Comment by yg** [comment]
@bdougie Done, tests are working fine! :tada:

**Comment by bdougie** [comment]
Thanks @yg

**Pull request merged**
