### PR TITLE
feat: adjust footer with hot open sauced template

### LINKED ISSUE #1408: Feature: Copy hot.opensauced.pizza footer
### Type of feature

🍕 Feature

### Current behavior

Screen Shot 2022-04-01 at 3 31 27 PM

We should remove external links and place them in the footer. 

### Suggested solution

Screen Shot 2022-04-01 at 3 30 49 PM

Copy the footer from https://github.com/open-sauced/hot

### Additional context

You can replace this footer.
Screen Shot 2022-04-01 at 3 37 02 PM

https://github.com/open-sauced/open-sauced/blob/main/src/styles/Footer.jsx

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by 0-vortex**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR adds the hot open sauced footer, adjusts header links and adds some icons.

## Related Tickets & Documents

closes #1408 

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
screenshot

Can you remove the "sauced." That will make the footer icons the focus. Also need these to be black in light mode. 

<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 100.0.4896.60 on Mac OS 10.15.7
Viewport:  1143 x 628 @3x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1415--open-sauced.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=100.0&resolution=1143x628&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1415--open-sauced.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6248ebaa690e220008a71e09&commentID=6248ee41cf41f73c1e1b4895&resolution=resolved)

**Comment by 0-vortex** [comment]
> screenshot
> 
> Can you remove the "sauced." That will make the footer icons the focus. Also need these to be black in light mode.
> 
> Browser metadata
> ```
> Path:      /
> Browser:   Chrome 100.0.4896.60 on Mac OS 10.15.7
> Viewport:  1143 x 628 @3x
> Language:  en-US
> Cookies:   Enabled
> ```
> 
> [Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1415--open-sauced.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=100.0&resolution=1143x628&speed=1&start=true&ref=netlify-source)
> 
> [Open Deploy Preview](https://deploy-preview-1415--open-sauced.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6248ebaa690e220008a71e09&commentID=6248ee41cf41f73c1e1b4895&resolution=resolved)

Should I remove that completely? Saw the previous footer was alternating with this. Fixing dark mode now :D

**Comment by bdougie** [comment]
We can remove it altogether. You can also remove the Blog and Docs links in the nav and move the blog link to the footer.

I think docs can be added to the user dropdown instead and/or the footer. 

Screen Shot 2022-04-03 at 7 46 01 AM

**Comment by 0-vortex** [comment]
> We can remove it altogether. You can also remove the Blog and Docs links in the nav and move the blog link to the footer.
> 
> I think docs and "report an issue" links can be added to the user dropdown instead and/or the footer.
> 
> Screen Shot 2022-04-03 at 7 46 01 AM

Just to clarify, that leaves the header navigation empty.

**Comment by bdougie** [comment]
Correct I am working with a designer and came to the conclusion 

External links in the footer and other links in the drop down.

We will most likely add the search bar there

**Comment by 0-vortex** [comment]
latest commits should cover everything, not sure about the positioning for the docs link tho (uppercase vs lowercase chars)

**Review by bdougie — APPROVED** [review]
LGTM. There will be future iterations but this works for now.

**Pull request merged**
