### PR TITLE
style: change IssueClosedIcon from gitRed to gitPurple

### LINKED ISSUE #1321: Feature: match new issue colors in contributions
### Type of feature

Style

### Current behavior

Currently in our contributions rendering, we use a red icon for closed issues.
Screenshot of current icon colors

GitHub recently changed their colors as it relates to issues.

https://github.blog/changelog/2021-10-26-updates-to-our-issue-status-icons-and-colors/

### Desired solution

Update the code to reflect the new closed issue color (purple), along with other relevant updates.

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by AlexJanow**
## What type of PR is this? (check all applicable)

- [x] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

Change color of closed issue icon to purple

This PR [adds/removes/fixes/replaces] this [feature/bug/etc]. 

## Related Tickets & Documents

Fixes #1321
## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 docs
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by mtfoley** [comment]
@AlexJanow thanks for the PR! I'd love to know if you had any feedback on the compliance check comments!

**Comment by mtfoley** [comment]
Normally, we look for screenshots showing visual changes - however this particular feature can be a little tricky to get screenshots of.
So for other reviewers, here's light mode:
image
and Dark mode:
image

**Comment by AlexJanow** [comment]
> @AlexJanow thanks for the PR! I'd love to know if you had any feedback on the compliance check comments!

@mtfoley Thank you for your feedback and the screenshots! 
This was my first real PR to open source so I missed some parts initially, but the compliance check comments showed me what needed to be edited, so all good :+1:

**Comment by mtfoley** [comment]
I edited the title. The issue was originally listed as a feature, and we don’t explicitly suggest it in any of the compliance checks but this PR is probably a “style” change, rather than “fix”. Just some housekeeping.

**Comment by mtfoley** [comment]
LGTM!

**Pull request merged**
