### PR TITLE
fix: 1046-fix-dashboard-search-bar-overlap-mobile

### LINKED ISSUE #1046: Bug: Fix dashboard search bar overlap mobile
### Describe the bug

The search bar overlaps with the sort panel function.

### To Reproduce

1. Log in
2. Scroll down to the add repository box

### Expected behavior

The 2 sections should switch to block level elements and not overlap each other.

### Screenshots

image

### Smartphone

- Device: Iphone SE2
- OS: 14
- Browser: Safari

### PR DESCRIPTION
**Pull request by miralsuthar**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [x] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

fix: This PR fixes dashboard search bar overlap mobile bug by integrating some CSS in search style and sort option. 

## Related Tickets & Documents

fixes #1046

## Mobile & Desktop Screenshots/Recordings

image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 docs
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
Hey @miralsuthar thanks for jumping on this. Quick note, you click the checkboxes in the markdown instead of using emojis ✔️

https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

**Comment by miralsuthar** [comment]
Hey, @bdougie I have filled the form. can you take a look at that?

**Review by filiptronicek — APPROVED** [review]

**Comment by filiptronicek** [comment]
Works as expected!

<summary>
Screenshot
<details>

deploy-preview-1059--open-sauced netlify app_(Pixel 2 XL)

</details
</summary>

**Comment by miralsuthar** [comment]
Hey, @bdougie I have fixed the issue can you take a look at it and let me know if you need any changes.

**Review by bdougie — APPROVED** [review]
LGTM

**Pull request merged**
