### PR TITLE
docs(good first issues): updates triage guide

### PR DESCRIPTION
**Pull request by bdougie**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [x] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

My philosophy on `good first issues` is that they should include solutions or helpful tips to point folks to ways to solve the problems relatively easily. 

- Issues that `needs triage` cannot be labeled as `good first issues`
- It is better to have no `good first issues` labeled than to have a `good first issue` confusing enough to deter a contributor from contributing. 

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [x] 📓 docs
- [ ] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

rules gif: add )

### CODE REVIEW

**Comment by bdougie** [comment]
FYI, adding this mainly because I think we have too many good first issues and not enough folks grabbing them. Our good first issues get published on Twitter with the goodfirstissues bot. 

In the future, it may make sense to publish these to the saucedopen Twitter.

**Comment by 0-vortex** [comment]
that makes a lot of sense, was confused between the ramp up time it takes to contribute and the issue difficulty levels themselves - what constitutes a good first issue so tried to identify some chores that can be used to learn the project easily and left them open.

would you be willing to go through some of the previously completed good first issues one stream and give triaging feedback ? 😀

**Comment by mtfoley** [comment]
Wondering if a label "backend" or "onegraph" would be helpful or redundant to the labels we already have. Shouldn't be many issues that fit it.

**Comment by 0-vortex** [comment]
> Wondering if a label "backend" or "onegraph" would be helpful or redundant to the labels we already have. Shouldn't be many issues that fit it.

#1047 👀

**Pull request merged**
