### PR TITLE
feat: Adds Repo suggestions to the onboarding flow

### PR DESCRIPTION
**Pull request by chadstewart**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR adds the feature of repo suggestions in onboarding. 

## Related Tickets & Documents

Adds #1428

## Mobile & Desktop Screenshots/Recordings

Screenshot from 2022-05-23 20-06-28
Screenshot from 2022-05-23 20-06-41
Screenshot from 2022-05-23 17-31-04

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [x] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by bdougie — CHANGES_REQUESTED** [review]
1. We can lose the girl in mobile view
2. Left align buttons and text (especially in mobile)
3. Always use the fullName - i.e. open-sauced/open-sauced. Use doesn't know what `cli` is.

**Comment by bdougie** [comment]
> * Left align buttons and text (especially in mobile)

On second thought this should 💯 be left aligned but also, each button should be on the same line and have a natural break for screen width.

**Comment by chadstewart** [comment]
> 1. We can lose the girl in mobile view
> 2. Left align buttons and text (especially in mobile)
> 3. Always use the fullName - i.e. open-sauced/open-sauced. Use doesn't know what `cli` is.

Made those changes you requested @bdougie!

**Review by bdougie — APPROVED** [review]
Looks good for now. Going to merge for the sake of moving on.

**Pull request merged**
