### PR TITLE
Add Crisp Chat

### PR DESCRIPTION
**Pull request by yg**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Release

## Description

As discussed in Twitch Stream, here is the dummy implementation of crisp in open sauced.

PS: Currently I linked with my account!

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

Screenshot from 2020-06-07 13-54-33

## Added tests?

- [ ] yes
- [ ] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] readme
- [ ] no documentation needed

### CODE REVIEW

**Comment by filiptronicek** [comment]
Could the colors be changed to open-sauced ones? @yg

**Comment by yg** [comment]
> Could the colors be changed to open-sauced ones? @yg

Yes, @filiptronicek everything is customizable (color, icon, bg pattern, etc), for now, I tested with my crisp account!

**Comment by bdougie** [comment]
They for throwing this together @yg. 

I love the idea of having live chat for users, especially those looking for help getting started. I don't I love the idea of managing a Crisp account or team. 

A perfect chat integration would include the ability to add a team in the org like @open-sauced/support and link the chat to a discord channel and link it to where the thread of conversation. 

Is there a to add a webhook to the discord channel in discord and have a response a way to automate the way a support team would have access to this service.

**Comment by yg** [comment]
@bdougie Nice Idea!

Yes, using Crisp and maintaining a separate team will be hard and not recommended!

I think we need to develop a special bot for GH Discussions and Discord Integration.

@NotMoni is a bot developer, I think he might help us to achieve this.

**Comment by yg** [comment]
My idea is!

The steps are

1. Created a new discussion in GitHub
2. The bot should create a new private channel in Discord under support category
3. The bot platform should be synchronous on both GitHub and Discord
4. If the discussion is marked as answer, the channel in discord should get deleted

This is the flow, WDYT @bdougie, @NotMoni

**Comment by NotMoni** [comment]
> My idea is!
> 
> The steps are
> 
>     1. Created a new discussion in GitHub
> 
>     2. The bot should create a new private channel in Discord under support category
> 
>     3. The bot platform should be synchronous on both GitHub and Discord
> 
>     4. If the discussion is marked as answer, the channel in discord should get deleted
> 
> 
> This is the flow, WDYT @bdougie, @NotMoni

I can do that.

**Comment by NotMoni** [comment]
If we message in the discord channel should it get posted in the discussion also ?

**Comment by yg** [comment]
> If we message in the discord channel should it get posted in the discussion also ?

@NotMoni Yet it's two-way communication!

**Comment by NotMoni** [comment]
@yg How do u suggest we send a message in the discussion?

I can do something like, on webhook => post message.
Then once we post a message on discord => `how does the message get send in the discussion`

via webhook? 
via a GitHub app? 
or something else like a webhook to post messages on GitHub discussions.

**Comment by bdougie** [comment]
> The bot platform should be synchronous on both GitHub and Discord

@yg I like that path, but GitHub has not shipped an API for Discussions yet, we would either have to wait on that aspect and stick with discord or get creative with puppeteer or playwright. 

I love the idea of the short-lived channel. 

I also see the free plan for Crisp does not allow customization to the widget. $25 a month is doable, but as mentioned previously in chat, I want to limit the number of things I am paying for out of pocket. Having the customized version is fine. I would be happy to pay for it when we hit the 1.0.0 milestone. By then, I hope to start taking on outside funding or sponsors.

**Comment by bdougie** [comment]
> @yg I like that path, but GitHub has not shipped an API for Discussions yet, we would either have to wait on that aspect and stick with discord or get creative with puppeteer or playwright.

Actually, we can sync it to an issue and just hit the convert to the discussion button when the conversation is answered.

**Comment by NotMoni** [comment]
> > @yg I like that path, but GitHub has not shipped an API for Discussions yet, we would either have to wait on that aspect and stick with discord or get creative with puppeteer or playwright.
> 
> Actually, we can sync it to an issue and just hit the convert to the discussion button when the conversation is answered.

Can we send messages to issues with a webhook or something like that?

**Comment by yg** [comment]
> Can we send messages to issues with a webhook or something like that?

I think webhook is best suitable! @bdougie what is your point here?

**Comment by bdougie** [comment]
To create an incoming payload, we could use [repository_dispatch](https://developer.github.com/webhooks/event-payloads/#repository_dispatch) to update the issue comment thread from discord/crisp.

**Comment by yg** [comment]
@bdougie Can we close this and move to discussion?

**Comment by bdougie** [comment]
https://github.com/open-sauced/open-sauced/discussions/682

**Pull request closed without merging**
