### PR TITLE
Add plural/singular to number of languages

### PR DESCRIPTION
**Pull request by filiptronicek**
## What type of PR is this? (check all applicable)

- [x] ♻️ Refactor
- [ ] ✨ Feature
- [x] 🐛 Bug Fix
- [x] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description
If the number of languages is, for example, 20, it will show (3)+17 languages
torvalds/linux
If the number of languages is just +1, it will show +1 language
aperta-principium/Interclip

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by yg** [comment]
@filiptronicek Thanks for the PR! :purple_heart: 

I already thought of doing it!

**Comment by yg** [comment]
@filiptronicek Can you make the same for participants?

https://github.com/open-sauced/open-sauced/pull/616/files#diff-d2bf322ce2d446f4e713b6ea7834714fR48

**Comment by filiptronicek** [comment]
Sure! @yg

**Comment by yg** [comment]
Perfect @filiptronicek :+1:

**Comment by bdougie** [comment]
Not sure what happened here. Apologies on closure of this @filiptronicek, can you reopen this?

**Pull request closed without merging**
