### PR TITLE
Safari UI vertical alignment fix, Illustrations top and bottom margins

### LINKED ISSUE #756: Bug: Safari making app screens a bit too large
### Describe the bug
On Safari, a lot of the sections of the app are a bit too big.
### To Reproduce

1. Go to the Dashboard / repo with Safari
1. See the bug

### Expected behavior
The same as in every other browser
### Screenshots
dashboard view

repo view

### Desktop

- OS: macOS Catalina
- Browser: Safari 
- Version: macOS Catalina

### PR DESCRIPTION
**Pull request by GiselleDZ**
## What type of PR is this? (check all applicable)
- [x] 🐛 Bug Fix

## Description
* Resolved excessive spacing around illustrations in three of the pages listed on the issue: 
1- Dashboard with repos
2- Dashboard without repos
3- Repositories

* The spacing was due to a Safari default item alignment, either "center" or "baseline". I resolved it by aligning items "flex-start".
* Created a new styled component called SpaceBetweenTop, based on SpaceBetween. The new styled component is in src > styles > grid > flex.js
* Replaced the styled component in three React Components:  
1- CreateGoals.js
2- RepositoryGoals.js
3- Repository.js

## Related Tickets & Documents
Fixes #756  https://github.com/open-sauced/open-sauced/issues/756

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
The fix on Safari Dashboard:
Screen Shot 2020-10-15 at 2 29 02 PM

The fix on Safari Repos:
Screen Shot 2020-10-15 at 2 33 55 PM

Fix doesn't affect mobile/responsive, which doesn't show an illustration : 
Screen Shot 2020-10-15 at 2 31 40 PM

Mobile / Responsive on Chrome still work: 
Screen Shot 2020-10-15 at 1 15 50 PM
Screen Shot 2020-10-15 at 1 15 28 PM
Screen Shot 2020-10-15 at 1 15 15 PM

## Added tests?
- [x] 🙅 no, because they aren't needed

## Added to documentation?
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?
Main branch tests were not passing, so my branch tests aren't either. See screenshot:
Screen Shot 2020-10-15 at 1 09 52 PM

## [optional] What gif best describes this PR or how it makes you feel?
awkwafina award

### CODE REVIEW

**Comment by bdougie** [comment]
Thanks @GiselleDZ for opening this PR, I am reviewing it now.

**Review by bdougie — APPROVED** [review]
LGTM, I will wait on the @open-sauced/triage for a second look.

**Review by filiptronicek — APPROVED** [review]
Cool stuff, LGTM

**Comment by BlueJYT** [comment]
I'm glad that this issue was solved quickly! 🥳 🎉

**Pull request merged**
