### PR TITLE
feat: update docusaurus config for Algolia

### LINKED ISSUE #1106: Enable Docsearch on docs.opensauced.pizza
# What is this?

I just confirmation from Algolia that we have access to their free docsearch tool. They will crawl the docs site and share the search results.

https://github.com/algolia/docsearch-configs/blob/master/configs/opensauced.json

# Implementation

Docusaurus supports search using Algolia DocSearch. Once your website is online, you can submit it to DocSearch. Algolia will then send you credentials you can add to your siteConfig.js.

- [Instruction to implement](https://v1.docusaurus.io/docs/en/search)
- Create siteConfig.js in the [root of the docs](https://github.com/open-sauced/open-sauced/tree/main/docs) folder

```js
const siteConfig = {
  ...
  algolia: {
    apiKey: '1691a4a5b06166984397aa30153f663c',
    indexName: 'opensauced',
    algoliaOptions: { 'facetFilters': ["type:$TYPE"] },
    debug: false // Set debug to true if you want to inspect the dropdown
  },
  ...
};

```

### PR DESCRIPTION
**Pull request by mtfoley**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description
Updating docusaurus config per Algolia settings provided in #1106. 

## Related Tickets & Documents

This PR fixes #1106 

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [x] 📓 docs
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

Test whether algolia search works!

## [optional] What gif best describes this PR or how it makes you feel?
because dinosaurs

### CODE REVIEW

**Comment by mtfoley** [comment]
@0-vortex I needed to tweak the config things because the Algolia instructions looked like they were written for Docusaurus v1 and we are on v2. Also needed to install the search plugin (it's pretty!).

I don't think I'm up to speed on how docusaurus deploy works TBH.

**Comment by 0-vortex** [comment]
> @0-vortex I needed to tweak the config things because the Algolia instructions looked like they were written for Docusaurus v1 and we are on v2. Also needed to install the search plugin (it's pretty!).
> 
> I don't think I'm up to speed on how docusaurus deploy works TBH.

There is no real testing right now but after semantic-release would split the docs into their own repo like explore and then we would have the same patterns as open-sauced

**Review by filiptronicek — APPROVED** [review]
LGTM ✅

**Comment by 0-vortex** [comment]
> LGTM ✅

+1

**Pull request merged**
