### PR TITLE
PWA Implementation

### LINKED ISSUE #669: Feature: Progressive Web App
### Is your feature request related to a problem? Please describe.

Implement Progressive Web App for Open Sauced

We can ship :shipit: as both **mobile** and **web** progressive app!

- Mobile Compatible
- Desktop Compatible

### PR DESCRIPTION
**Pull request by yg**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [x] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

PWA Implementation #669 

## Related Tickets & Documents

Closes #669 

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

https://www.loom.com/share/4091b0cf817d473f9f2d7e8db9228ac8

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

|  **Before**  |  **After**  |
|---|---|
|  Screenshot (2)  |  Screenshot  |

### CODE REVIEW

**Comment by yg** [comment]
@bdougie It works

Screenshot from 2020-06-14 10-16-01

**Comment by yg** [comment]
@bdougie this image is not in a perfect square, is there any other image?

**Comment by bdougie** [comment]
logo

This is 288x288

**Comment by yg** [comment]
|  **Before**  |  **After**  |
|---|---|
|  Screenshot (2)  |  Screenshot  |

**Comment by yg** [comment]
> but our performance dropped to 83

@NotMoni Weird! Looking on that!

**Comment by bdougie** [comment]
I think there is something causing the performance to be inconsistent. I don't think it is this branch.

**Comment by NotMoni** [comment]
ok

**Pull request merged**
