### PR TITLE
Change homepage screenshot

### PR DESCRIPTION
**Pull request by filiptronicek**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [x] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description
Change the homepage screenshot to reflect the new UI

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
new image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by filiptronicek** [comment]
@NotMoni It's grey by default, I think people are mostly used to seeing this, but I can try it for sure!

**Comment by NotMoni** [comment]
ok, cool. I think the background should be `#f6eace`

**Comment by filiptronicek** [comment]
For reference: https://www.cnet.com/news/say-good-bye-to-that-green-secure-lock-on-google-chrome/

**Comment by NotMoni** [comment]
alright
what about https://github.com/open-sauced/open-sauced/pull/678#issuecomment-643814597

**Comment by filiptronicek** [comment]
@NotMoni Probably a problem on my end, but I cannot see the changes you suggested, any ideas why?
image

**Comment by filiptronicek** [comment]
Here's a quick mock of a shadow, WDYT @yg 
opensauced-homepage

**Comment by filiptronicek** [comment]
Perhaps would be better with the shadow being on all sides.....

**Comment by bdougie** [comment]
For context, the screenshot I took is [using the macOS shorcut](https://support.apple.com/en-us/HT201361#:~:text=Press%20and%20hold%20these%20keys,or%20menu%20to%20capture%20it.).

There may be someone on the internet that has figured out to mimic that blur/shadow. I personally prefer it since it takes you out of the README and gives you a better experience than the cropped version.

**Comment by filiptronicek** [comment]
Can anyone help me with this? Or any ideas how to resolve this

**Comment by bdougie** [comment]
@filiptronicek can you edit this photo instead. 

Screenshot 2020-06-17 07 41 10

**Comment by filiptronicek** [comment]
Nice, done, only one problem, I cannot push to the base repo anymore. Is it possible to remap it to another branch/repo?
image
image(19)

**Comment by yg** [comment]
@bdougie What about **Storybook** screenshot?

@filiptronicek

**Comment by bdougie** [comment]
> @bdougie What about Storybook screenshot?

Screenshot 2020-06-17 23 07 57

**Comment by filiptronicek** [comment]
@bdougie can you somehow change the base of the pr? I can't commit here anymore. Should we close and reopen this?

**Comment by bdougie** [comment]
We can just merge this since it has been orphaned due to the disappearing fork.

**Pull request merged**
