### PR TITLE
feat: add GitHub action to check for linked issues

### PR DESCRIPTION
**Pull request by jlengstorf**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR [adds/removes/fixes/replaces] this [feature/bug/etc]. 

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 docs
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by mtfoley** [comment]
LGTM ;-p

**Comment by 0-vortex** [comment]
can give this a spin if you push the code you were testing on stream or link to it

**Comment by bdougie** [comment]
Hey @0-vortex the code is here. https://github.com/jlengstorf/open-sauced/pull/1/files

But considering this was for the stream, I think we can abandon this PR and you can start from where we left off.

**Comment by bdougie** [comment]
Video is live https://www.youtube.com/watch?v=zNizVeJbTwQ&t=3876s

**Pull request closed without merging**
