### PR TITLE
Updated Favicon

### LINKED ISSUE #716: Bug: Outdated favicon
### Expected behavior
Favicon should be updated as per latest logo design

### Screenshots
image

### PR DESCRIPTION
**Pull request by JapneetSingh5**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [x] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description
Updated favicon to the new open-sauced logo 🍕 

## Related Tickets & Documents

fixes #716

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

Screen Shot 2020-06-22 at 10 27 59 PM

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by JapneetSingh5** [comment]
sorry i forgot to mention the issue, i.e. #716

**Comment by JapneetSingh5** [comment]
@yg I think this will do it, please check once and ill make the needed changes

**Comment by yg** [comment]
@JapneetSingh5 You seems like committed lint stuffs too 🤔

**Comment by JapneetSingh5** [comment]
oh, but there were not conflicts

**Comment by bdougie** [comment]
@JapneetSingh5 thanks for your contribution to Open Sauced

**Pull request merged**
