### PR TITLE
Add husky and format existing code base

### PR DESCRIPTION
**Pull request by jsparmani**
## What type of PR is this? (check all applicable)

- [x] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description
Format existing code base and setup husky with prettier formatting config.

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by filiptronicek** [comment]
Doesn't seem that the formatting is working, does it work locally?

**Comment by yg** [comment]
I think the deploy is failing, cuz it violates the **eslint rules**!

Screenshot

**Comment by jsparmani** [comment]
Yes, works locally on staged files, but it's failing because of eslint as @yg said. Should I change eslint settings to go inline with prettier linting configs?

**Comment by bdougie** [comment]
Is there a way for pretty-quick to use the existing .eslintrc? It seems like it is applying changes based on a different config.

**Comment by bdougie** [comment]
@jsparmani, sorry but we are going to have to close this. Husky may not be the direction we need. I went ahead and went with this solution because it was a smaller step towards fixing bigger issues. https://github.com/open-sauced/open-sauced/pull/704

If you would like to work on another open issue, please feel free to ask questions in the discord.

**Pull request closed without merging**
