### PR TITLE
feat: Server Side Rendered Repository Pages

### PR DESCRIPTION
**Pull request by jasonericdavis**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR adds the feature of server-side rendered (SSR) repository pages. 
- To prerender all of the pages run the command `npm run prerender`. The output will added to `build/client/repos`
- For local development run the command `npm run dev:ssr`

## Mobile & Desktop Screenshots/Recordings

SPA rendered pages will keep the same look and feel. 
The SSR pages will be similar to the SPA rendered rendered pages with some of the data missing that is not available at time of render.  Below is a screenshot of a SSR page.

image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [x] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?
image

### CODE REVIEW

**Comment by jasonericdavis** [comment]
This PR represents what I have done so far hence it still being in a draft state. 

 I initially tried the [vite-ssr plugin](https://github.com/frandiox/vite-ssr) but the documentation didn't provide enough detail to get past fetching data prior to server side rendering. I switched to use [vite-plugin-ssr](https://vite-plugin-ssr.com/) which has more documentation. 

Currently I am up to the point where I can fetch the data prior to server-side rendering. The work that is left to do is around styling the page to keep the same look and feel as the app itself.

**Comment by bdougie** [comment]
Curious how much complexity we would add for contributors with this addition. Also I assume we would need to explore a new deployment strategy with this implementation. Something like Railway or Digital Ocea?

**Comment by 0-vortex** [comment]
> Curious how much complexity we would add for contributors with this addition. Also I assume we would need to explore a new deployment strategy with this implementation. Something like Railway or Digital Ocea?

Not at all, the SSR render a static page we cache, it's all still static. Never ever turn React into s backend that's the recipe for failure or success with something other than you started 😁

**Comment by jasonericdavis** [comment]
Does this mean that we want to pre-render the repository pages to include in the build that gets uploaded to netlify?

**Comment by 0-vortex** [comment]
> Does this mean that we want to pre-render the repository pages to include in the build that gets uploaded to netlify?

Exactly, don't want to create a side-tech, just pass 3500 repo props to the repo page - yes I know how it sounds :>

**Comment by jasonericdavis** [comment]
Cool I will add that.

**Comment by jasonericdavis** [comment]
This should work now. To prerender all of the pages run the command `npm run pretender`

**Comment by bdougie** [comment]
We should sync on this @jasonericdavis. This work happened while I was heads down quitting my last job. Curious if this pattern would work for this project https://github.com/open-sauced/hot/discussions/217#discussioncomment-3200803

**Comment by jasonericdavis** [comment]
Cool just let me know what you need from me

**Comment by bdougie** [comment]
https://github.com/open-sauced/open-sauced/issues/1491

**Pull request closed without merging**
