### PR TITLE
feat(WIP): remirror note

### PR DESCRIPTION
**Pull request by mtfoley**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR is meant to add social editor for #769. I know I'm going to run into a need to change tests because that's where this got hung up in past PRs.

@0-vortex At this point, I can't get app to start because eslint is choking on something way down the stack. Maybe you'll see something you know how to navigate.
Screen Shot 2021-06-29 at 9 51 23 PM

## Related Tickets & Documents

#769 
## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 docs
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by 0-vortex** [comment]
Did not finish checking this last night but the first issue that made your lockfile unreadable locally was #1064 

Peer dependencies of added libraries:
-  [remirror/editor-social](https://github.com/remirror/remirror/blob/64ae07a7030286006fd7a16913ee4c13cdceb540/%40remirror/editor-social/package.json#L37)
- [storybook-dark-mode](https://github.com/hipstersmoothie/storybook-dark-mode/blob/9227bccd065e7d04d4f9d9f79385e8591828d5ae/package.json#L29-L35)

Storybook add-on addition should not influence any of the existing dependency tree, just add some packages to it.

For Remirror we need to update the code to `react@17` in the upstream or fork and resolve it from GitHub in `package.json`. It's a very small fix anyone can do but it can get difficult to coordinate, let me know how you want to handle this !

**Comment by 0-vortex** [comment]
Permalinks didn't work for me today, anyone know what I'm doing wrong ? :<

**Comment by 0-vortex** [comment]
Dropping `@remirror/editor-social@^0.13.1` in favour of `@remirror/react-social@^1.0.0-next.60` should fix it :D
^ this potentially implies cherry picking on top of the dependencies fix

**Comment by mtfoley** [comment]
I think I may have started with that one and hit a different dead end. I’ll try again…

**Comment by mtfoley** [comment]
Closing this bc I need to start over with a fresh fork.

**Pull request closed without merging**
