### PR TITLE
release v0.17.0

### PR DESCRIPTION
**Pull request by bdougie**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [x] 🔖 Release
- [ ] 🚩 Other

## Description
This release is plan for 7/15/2020. 

## Related Tickets & Documents
https://github.com/open-sauced/open-sauced/issues/668
https://github.com/open-sauced/open-sauced/issues/762

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
image

@yg Small oversight on my part. The description loader box does not respect the width on mobile.

**Comment by yg** [comment]
@bdougie I think we need to remove hard width! Let me try!

**Comment by filiptronicek** [comment]
Merged master to the release. Resolved a conflict. Should be OK now

**Comment by yg** [comment]
/cc @filiptronicek 

Screenshot

**Comment by yg** [comment]
> @yg Small oversight on my part. The description loader box does not respect the width on mobile.

@bdougie Fixed this!

**Comment by yg** [comment]
> /cc @filiptronicek
> 
> Screenshot

@filiptronicek Fixed this in ede8739 :)

**Pull request merged**
