### PR TITLE
fix: added proper release management resolution

### LINKED ISSUE #1040: Bug: latest update dependency resolution was incomplete
### Describe the bug

lastest update dependency resolution was incomplete, updating to `onegraph-apollo-client@3.1.2` with the audit issues we ended up reverting that to `2.2.2` and build resolution broke.

### To Reproduce

```
npm ci
npm run build
```

### Expected behavior

It should work.

### Screenshots

[It doesn't](https://app.netlify.com/sites/open-sauced/deploys/60c92eb202b23c41c03fe526).

### Desktop

- OS:
- Browser:
- Version:

### Smartphone

- Device:
- OS:
- Browser:
- Version:

### Additional context

Blocks #1021

### PR DESCRIPTION
**Pull request by 0-vortex**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [x] 🐛 Bug Fix
- [x] 👷 Optimization
- [ ] 📝 Documentation Update
- [x] 🔖 Release
- [ ] 🚩 Other

## Description

The commit containing the code for [0.21.6-pr](https://github.com/open-sauced/open-sauced/commit/31c49222025bcac56a620cd8206727c0aa1539d5) was rewritten by the GitHub resolve conflicts button, it fast forwarding the maintainer branch and subsequently the release from [0.21.6-ci](https://github.com/open-sauced/open-sauced/commit/78ef2fb8affe8fadff0f6abd1ed6da184feb07d0) effectively removed the missing dependencies AND changed `lockfileVersion` back to 1.

This might need some manual conflict resolution - and it is advised lockfiles get moderated by maintainers or, if the button configuration can be changed, for example never being used, several steps can be taken to protect that from happening again !

## Related Tickets & Documents

Fixes #1040 permanently, might require @bdougie to manually bump `package.json` version and subsequent `npm install`

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 docs
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

- stop the `build` and `release` steps in `ci.yml` from diverging by making `release` re-use the previous step
- `sed` the release to make it check the release action doesn't change anything but the `version` property in `npm-shrinkwrap.json` - having a bust dependency tree get merged creates more problems than having to open a new issue after X pull request was merged but the code was incomplete (it's always possible the rest of the code was proper so this method emulates incident reporting and management)
- document the resolve conflicts button in the UI to prevent this from happening in the future since there are more people with push access that could replicate the issue as a first-timer/one-off without this

### CODE REVIEW

**Comment by mtfoley** [comment]
Updated title to satisfy semantic release.  There’s really only one good first issue at the moment so it’s prob as good a time as any

**Comment by bdougie** [comment]
thanks for digging into this @0-vortex

**Comment by 0-vortex** [comment]
@filiptronicek this is the highest priority pull request right now, CI fixed but storybook configuration broken since unknown merge.

Merging this in could help solve the "resolve conflicts cascade" for the other PRs. 
Any chance you could review this ? Already started working on storybook on the docusaurus branch since it had eslint and babel updates :<

**Review by filiptronicek — APPROVED** [review]
@0-vortex this looks good, I think it's ready to go!

**Pull request merged**
