### PR TITLE
Add required params

### LINKED ISSUE #688: Bug: 404 not found... literally
### Describe the bug
When 

### To Reproduce
1. Go to opensauced.pizza
1. Append /repos/`your username`/`some random string` to the URL

### Expected behavior
The default 404 page is shown

### Screenshots
image

### Additional context
Probably a problem with the routing ->seems that the router gets confused when a repo is not present your goals.

### PR DESCRIPTION
**Pull request by filiptronicek**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [x] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description
Add required URL parameters, so that passing invalid arguments doesn't break the whole thing.

## Related Tickets & Documents
Fixes #688 

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

## What gif best describes this PR or how it makes you feel?
Alexandre Bobeda GIF

### CODE REVIEW

**Comment by yg** [comment]
@filiptronicek Instead of landing to the homepage if the repo is wrong we can fallback to 404!

**Comment by filiptronicek** [comment]
> 
> 
> @filiptronicek Instead of landing to the homepage if the repo is wrong we can fallback to 404!

If I understood correctly, that means, that if the URL pattern is correct, but it doesn't lead to an existing repo, it should also go to the 404? @yg

**Comment by yg** [comment]
> If I understood correctly, that means, that if the URL pattern is correct, but it doesn't lead to an existing repo, it should also go to the 404? @yg

Exactly @filiptronicek!

It will go to **404** when:

- If repo does not exist in GitHub
- The created goal does not belong to the current user (we can handle it in different PR later)

**Comment by filiptronicek** [comment]
Any idea how you would go about this? I always overthink these problems 🤣  @yg

**Comment by yg** [comment]
I have no Ideas about how to have 404 fallback :confused: 

/cc @bdougie

**Comment by filiptronicek** [comment]
Does the Repository.js even check whether the repo exists? @yg

**Comment by yg** [comment]
> Does the Repository.js even check whether the repo exists? @yg

No @filiptronicek!

**Comment by bdougie** [comment]
> The created goal does not belong to the current user (we can handle it in different PR later)

My thought, which is not covered in the issue, so all new info. 

- A user should be able to see any repo as long as they logged in.
- If they are not tracking that repo in their goals, they should only see add this repo button
- If they are not tracking that repo in their goals, they should not see the notes or contributions section (the whole side bar probably). 

I am considering that you can see any GitHub repo without being logged in, so you should be able to see any repo with open sauced without tracking. They need to log in so we can use their GitHub token :)

**Pull request merged**
