### PR TITLE
feat: Onboarding tooltip

### PR DESCRIPTION
**Pull request by chadstewart**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR [adds] the [feature] of onboarding tooltip for 2nd onboarding step.

Currently, with the redesign of the onboarding flow, when the user is being onboarded and asked to create the database, they would click on the create database button and be redirected to GitHub with no instructions on what to do next. The tooltip is there to provide more context on what the user would need to do once they are redirected to GitHub. 

## Related Tickets & Documents

Adds #1433

## Mobile & Desktop Screenshots/Recordings

Screenshot from 2022-05-16 07-59-07
Screenshot from 2022-05-16 07-59-12
Screenshot from 2022-05-16 17-04-41

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [x] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by chadstewart** [comment]
@bdougie The tooltip work feels like it's in a good place right now. The branch can't be merged though because I believe there are some merge conflicts. I figured I'd wait until vortex's branch got merged into main before merging my branch as well.

**Comment by bdougie** [comment]
> This PR [adds] the [feature] of onboarding tooltip for 2nd onboarding step.

Need PR description.

**Review by bdougie — APPROVED** [review]
Looks great thanks for shipping this. Please also add more context to the Pr description.

**Comment by chadstewart** [comment]
> Looks great thanks for shipping this. Please also add more context to the Pr description.

Updated the description. Let me know if that's okay.

**Comment by bdougie** [comment]
This has placeholder text

> [adds] the [feature] 

Note, @mtfoley. I think a good feature for the PR Compliance action is checking for placeholder text and failing if it still exists.

**Comment by bdougie** [comment]
Ah, I see what you did. You left the `[]`. I skimmed it thinking it was untouched. 

Though I still think this would be a nice addition to the action.

**Comment by chadstewart** [comment]
> Ah, I see what you did. You left the `[]`. I skimmed it thinking it was untouched.
> 
> Though I still think this would be a nice addition to the action.

I'm not gonna lie, I didn't think about removing the [] brackets every time I updated the description, lol. I'll make sure to do that moving forward.

**Pull request merged**
