### PR TITLE
feat: change note form basic template to a link

### LINKED ISSUE #1159: Feature: Make the basic template not a button, but instead a link
### Type of feature

Fix

### Current behavior

Today it looks like this. 
Screen Shot 2021-09-22 at 2 12 02 PM

### Desired solution

It would be nice to have it as a standard link.

### Additional context

Look in the existing storybook or design system for how to do this. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by nayabatir1**
## What type of PR is this? (check all applicable)

- [x] ♻️ Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR changes the basic template to a link instead of a button.

## Related Tickets & Documents

Closes #1159 

## Mobile & Desktop Screenshots/Recordings

# Screenshots
### Before
image

### After
image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 docs
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

- Add prettier config file as each system has it's own config. Due to which a large portion of a file gets changed.
- After doing changes in ``NoteFromSocial.js`` as soon page reloads it crashes. Need to find a solution.
image

### CODE REVIEW

**Comment by mtfoley** [comment]
@nayabatir1 thanks for working on this! Here are a few things that would help move this along to merge:
- start the title of the PR with “feat:” or “fix:” (https://docs.opensauced.pizza/contributing/getting-started/#pull-requests)
- Since it was a visual change, a screenshot would be helpful  for reviewing 
after that we can look at approving the automatic checks.

**Comment by nayabatir1** [comment]
> @nayabatir1 thanks for working on this! Here are a few things that would help move this along to merge:
> - start the title of the PR with “feat:” or “fix:” (https://docs.opensauced.pizza/contributing/getting-started/#pull-requests)
> - Since it was a visual change, a screenshot would be helpful  for reviewing 
> after that we can look at approving the automatic checks.
> 

My bad, will do the necessary steps

**Comment by nayabatir1** [comment]
@mtfoley I've done necessary modification.

**Comment by mtfoley** [comment]
@nayabatir1 I approved the checks and it looks like those formatting changes made by prettier were caught by our implementation of eslint. So in order to get this passing I’d suggest:
- if you don’t already have it installed, install eslint `npm i -g eslint`
- try running `eslint —fix src/components/NoteFormSocial.js` and the hope would be that it puts code formatting back where it was.

**Comment by nayabatir1** [comment]
> @nayabatir1 I approved the checks and it looks like those formatting changes made by prettier were caught by our implementation of eslint. So in order to get this passing I’d suggest:
> - if you don’t already have it installed, install eslint `npm i -g eslint`
> - try running `eslint —fix src/components/NoteFormSocial.js` and the hope would be that it puts code formatting back where it was.

So after fixing formatting do I have to push my code again.

**Comment by mtfoley** [comment]
Yes please

**Comment by nayabatir1** [comment]
> Yes please

Done

**Comment by bdougie** [comment]
issues for the prettier config and error message would be appreciated.

I have been using prettier for awhile and have always leveraged the eslint plugin, but open to suggestions as I now IDEs have different expectations. 

The UI fix looks good too.

**Comment by 0-vortex** [comment]
Going to force a hard no on the linter as you are scope creeping here - please disengage all the lint stuff from this PR and discuss them first, potentially opening issues first. Like @mtfoley mentioned, we already have eslint, prettier is a quick dirty shortcut for using the IDE auto-format option instead of writing a proper configuration file or setting up the formatted with hooks. 

While we appreciate the energy, the actual change for this PR is changing `<Button onClick={startNewNote}>` into `<SubtleLink href="#" rel="noreferrer" onClick={startNewNote}>`, delaying this merge for linter issues is effectively stitching together multiple PRs/issues, something which ultimately hurts your contribution graph.

Please tackle the reload and code formatted suggestions as separate issues and/or pull requests. If I'm not missing anything critical on the button->link, let's fast forward this, single line of code change should not suffer days worth of delays! 🔥

**Comment by mtfoley** [comment]
I've added a discussion for the prettier config idea.

**Review by bdougie — APPROVED** [review]
LGTM

**Comment by bdougie** [comment]
Thanks for the work on this @nayabatir1. Much appreciated, also thanks for the discussions you started around prettier. Feel free to share  your thoughts on that here: https://github.com/open-sauced/open-sauced/discussions/1164

**Pull request merged**
