### PR TITLE
472 leverage textarea

### LINKED ISSUE #472: UI bug - Note box does not respect size contraints
Screenshot 2020-02-12 12 33 46

repro steps:

1. drag the note box bigger and see what happens.

### PR DESCRIPTION
**Pull request by bdougie**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Release

## Description
#586 was merged too soon. Turns out the TextArea styled-component contained some need CSS. This PR reverts back to using it. 

## Related Tickets & Documents
Fixes #472 

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
Screenshot 2020-05-31 21 46 46

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
@yg, when you have a moment, could you try out the deploy preview to confirm if looks good on your end.

**Comment by bdougie** [comment]
Added scroll and max width.

**Comment by yg** [comment]
@bdougie Again the same issue from **onegraph**!

Screenshot from 2020-06-03 09-04-50

**Comment by bdougie** [comment]
Weird. Something must of changed on their end. Instead of it identifying my netlify app it is requiring me to allow each deploy preview.

cc/ @sgrove has this come up with support?

**Comment by sgrove** [comment]
@yg @bdougie Thanks for this, checking it out now - we just added some more flexible rules to detect e.g. netlify previews / heroku reviews, so this probably is part of that!

**Comment by dwwoelfel** [comment]
Thanks for flagging the issue with OneGraph. We just deployed a fix and the login should work for you with the Netlify preview urls again.

**Comment by yg** [comment]
Thanks for the fix @sgrove @dwwoelfel 💜

**Comment by yg** [comment]
@bdougie, For now, it is good to go :+1: !

The width is fixed! But anyway it has a horizontal scroll!

**Pull request merged**
