### PR TITLE
525 page reload with cached login

### LINKED ISSUE #525: Reloading the page shows login page for a small time
Reloading the page shows login page for a small-time

https://www.loom.com/share/5fab6c11a7a648e599a1d42b73411d91

/cc @bdougie

### PR DESCRIPTION
**Pull request by bdougie**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Release

## Description
Setting a cookie to prevent home page loading on reload. 

## Related Tickets & Documents
Fixes #525

## Added tests?
TBD - soon

- [ ] yes
- [ ] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] readme
- [x] no documentation needed

## [optional] Are there any post deployment tasks we need to perform?
n/a - I decided against netlify functions and cookie storage due to the complexity.

### CODE REVIEW

**Comment by bdougie** [comment]
This is not finished. There is a bug is clearing the cache.

**Comment by bdougie** [comment]
@yg I change directions on this. I was going down the path of using a netlify function to set a cookie to see if the user is logged in, but it was all getting complicated. 

This method would also require that all local development within the app start building their functions locally so they could test even unrelated parts of the app. This is because the functions run on Netlify's edge network, a workaround would be introducing two dependencies, `netlify-lambda` and `netlify dev`. I just don't all that is needed right now to solve a bug. 

I made the decision to just set the boolean in local storage similar to the `isAdmin` flag, mainly for the sake of limiting the complexity. 

If you are interested I was using the project as a guide towards my implementation: https://github.com/shortdiv/jwt-generate as well as https://travishorn.com/netlify-lambda-functions-from-scratch-1186f61c659e

I am sure a netlify function and cookies will make sense in the future, but for now, I am going to opt for simplicity.

**Comment by yg** [comment]
Good Idea @bdougie, **localstorage** will work fine!

**Comment by yg** [comment]
@bdougie Seems like everything working fine! :tada:

**Comment by bdougie** [comment]
> @bdougie Seems like everything working fine! 🎉

Excellent, I will go and merge. I realize this test file is currently being skipped so adding effort in testing this will not be useful until https://github.com/open-sauced/open-sauced/discussions/408 is solved

**Pull request merged**
